# The title
title: RailRoad IDE

# Description, Needs to change lol
description: An IDE For Modders, By Modders

# This is the banner, not the logo but _config.yml is a strange place.
logo: temp_banner.png

# Leave this. If you want to change colours, use css.
theme: jekyll-theme-minimal
show_downloads: true